---
title: "Exam-1"
excecute:
  echo: true
  warning: false
  message: false
  error: false

format: 
  html:
    code-fold: true
---
## Loading Data
```{r, echo=TRUE, warning=FALSE, message=FALSE, error=FALSE}
library(tidytuesdayR)
library(tidyverse)
library(rnaturalearth)
library(mosaic)

tuesdata <- tt_load('2020-02-18')
fc <- tuesdata$food_consumption
```

## Data Exploration

```{r, echo=TRUE, warning=FALSE, message=FALSE, error=FALSE}
head(fc)
tail(fc)
dim(fc)
```

## Understanding Variables

```{r, echo=TRUE, warning=FALSE, message=FALSE, error=FALSE}
ggplot(fc, aes(x = consumption, y = co2_emmission)) +
  facet_wrap(~food_category)+
  geom_smooth()
```

## Grand RQ

```{r, echo=TRUE, warning=FALSE, message=FALSE, error=FALSE}
country_map <- map_data("world")

ggplot(fc, aes(map_id = country, fill = consumption)) +
  geom_map(map = country_map) +
  facet_wrap(~food_category) +
  scale_fill_viridis_c("Consumption (kg/person/year") +
  expand_limits(x = country_map$long, y = country_map$lat) +
  labs(title = "Food Consumption Around the World", caption = "Data from the TidyTuesday", alt = "Western Countries tend to eat alot more milk and cheese than the rest of the world") +
  theme_map() 
  
```
## Aditional Questions
Do countries on the coast eat more fish?

Which foods produce the most CO2?
